{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-exonerate
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - exonerate
    - python {{ python }}
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - qiime2 {{ qiime2_epoch }}.*

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_exonerate
    - qiime2.plugins.exonerate
  commands:
    - pytest --cov q2_exonerate --pyargs q2_exonerate

about:
  home: https://github.com/bokulich-lab/q2-exonerate
  license: BSD-3-Clause
  license_family: BSD
